### ISSUE TITLE
Add tests for numeric separator

### ISSUE THREAD

**Issue by rwaldron** [tc39/test262#1051]
Once the spec grammar is written, reference: https://github.com/samuelgoto/proposal-numeric-separator

**Comment by leobalter** [comment]
This is at least 4 months away to reach stage 3.  For cleanliness and
better tracking, I suggest Test262 should not hold issues for Stage <3
(unintended pun) proposals.

**Comment by littledan** [comment]
Proposals can advance multiple stages in a single meeting, and this one is relatively simple.

I came across this bug report when I was about to file another one, about tests for class fields. I thought it'd make sense to keep this in bugs so that we can make sure not to duplicate each other's work. Tests can hang out in PRs against test262 for a while and be useful for people who are collaborating on a proposal.

What if, rather than not filing bug reports, we made a label for what stage things are at, and you can filter things out by label? (I don't have permissions to make labels, so I can't do this organization myself, but if you give me permission...).

**Comment by leobalter** [comment]
That's right! I'm on vacation this week, but I will have this fixed on
Monday. In the meanwhile, @bterlson is the one who can add you to the tests
team on GitHub.

**Comment by bterlson** [comment]
@leobalter I've added @littledan to @tc39/test262
