### ISSUE TITLE
Room for improvement on async/await tests

### ISSUE THREAD

**Issue by littledan** [tc39/test262#1152]
I fixed a couple bugs for cases with async functions which should be syntax errors in V8 which didn't seem to have test262 coverage:

- Async function literals are invalid as destructuring targets, e.g.,
```js
let async function() { } = { };
function f(async function() {}) { }
```
- Async function declarations are disallowed in single-statement contexts, e.g.,
```js
if (false) async function f() { }
label: async function f() { }
```

Writing test262 tests here would be a good starter project!

**Comment by littledan** [comment]
Sorry, actually I was mistaken--it seems that there are tests that ensure that async functions and generators are permitted in single-statement contexts. Aren't these invalid?

**Comment by rwaldron** [comment]
> `Async function literals are invalid as destructuring targets, e.g.,`

Yes, just like function declarations (`let function() { } = { };`, `function f(function() {}) { }`) and we don't write tests for those either. Also, most Python code would produce a SyntaxError in V8 and we don't write tests for that. 


> it seems that there are tests that **ensure that async functions and generators are permitted in single-statement contexts**. Aren't these invalid?

(emphasis mine)

I think you're mistaken: 

- https://github.com/tc39/test262/blob/master/test/language/statements/labeled/decl-async-function.js
- https://github.com/tc39/test262/blob/master/test/language/statements/labeled/decl-async-generator.js
- https://github.com/tc39/test262/blob/master/test/language/statements/if/if-stmt-else-async-fun.js
- https://github.com/tc39/test262/blob/master/test/language/statements/if/if-stmt-else-async-fun.js

**Comment by littledan** [comment]
> Yes, just like function declarations (let function() { } = { };, function f(function() {}) { }) and we don't write tests for those either. Also, most Python code would produce a SyntaxError in V8 and we don't write tests for that.

OK, I can see your logic for not prioritizing this test--this isn't like an invalid destructuring assignment target where something is parsed one way, and then explicitly reparsed another way; instead, function declarations are simply not part of the grammar of BindingPatterns.

Anyway, would you be opposed to letting a test against this bug in upstream, if I sent out my V8 test?

> I think you're mistaken

I'm so sorry for wasting your time here, you're right, I was sloppily misreading my test infrastructure output.

**Comment by rwaldron** [comment]
> Anyway, would you be opposed to letting a test against this bug in upstream, if I sent out my V8 test?

@leobalter I can't find the discussion regarding a similar situation we encountered with SpiderMonkey—do you recall what the outcome was there?

> I'm so sorry for wasting your time here,

Don't sweat it, I'm sure there will come a day when I need your patience <3

**Comment by leobalter** [comment]
The problem here is keeping Test262 a deterministic test suite.

We could generate infinite cases with non matching syntax, they are all subjective to potential risk of the language not working as expected.

From my experience, I like to base every test case in the documentation. We have documented working syntax and we also have documented non working syntax. The lookAhead with negative parts is one of the best examples here.

WRT SpiderMonkey, we had a case matching a non-documented syntax that was behaving as a non-syntax error. It would be hardly predictable without the found bug.

While adding some cases might give an impression they are interesting, I wonder how long this could extend the complexity of Test262's own size and not being able to document why that test exists after a while.

Using the same case I mentioned above, in one year or less, without a matching documentation (ES specs), someone reading that test might not be able to justify why that test exists.

This is a known phenomenon and it is classified as an anti-pattern. I like to call it the Turtle on the tree. It's hard to tell why it is there, but turtles cannot climb on trees, someone put the turtle there for a reason, better not to remove it.

**Comment by littledan** [comment]
I guess this is a philosophical question. I just don't see regression tests as technical debt. If a bug occurred in a real implementation, that's a signal that it's somewhat likely to occur in another implementation, isn't it?We can document things by pointing to the bug thread in the description.

**Comment by leobalter** [comment]
Once again, this is subjective. The main problem is how this can be interpreted. Let's say an implementation starts accepting `CoverParenthesizedExpressionAndArrowParameterList` in a IfStatement instead of the simple `( Expression )`, or at least it accepts a trailing comma after `Expression`. On which spec we will document our test?

Cases will be like:

```js
/*---
esid: sec-if-statement
description: If expression cannot have a trailing comma:
info:
  The syntax does not preview a trailing comma

  IfStatement :
    if ( Expression ) Statement
negative:
  phase: early
  type: SyntaxError
---*/

if ( true, ) {}
```

This is a random case, there's no implementation accepting this syntax, so what I am covering?

I can have spec text to match:

```js
/*---
esid: sec-if-statement-static-semantics-early-errors
description: Throw a SyntaxError if the If statement is a labelled function.
info:
  The syntax does not preview a trailing comma

  IfStatement :
    if ( Expression ) Statement

  13.6.1 Static Semantics: Early Errors

  - It is a Syntax Error if IsLabelledFunction(Statement) is true.
negative:
  phase: early
  type: SyntaxError
---*/

if ( true ) foo: function bar() {}
```

---

I'm not going to be intolerant and deny anything to be part of Test262, but I really believe we should have documentation to reason every and each test case. The same subjectivity might be worth investigating if the specs should account for any non matching failures that once were implemented by mistake.

**Comment by littledan** [comment]
Is "there was a regression in a real implementation" a reason? If not, why not?
