### ISSUE TITLE
Split class-fields features tag for public or private fields

### ISSUE THREAD

**Issue by leobalter** [tc39/test262#1346]
We are tracking a single proposal, but I got a report from implementations this feature tag can help the development process splitting out between public and private fields.

**Comment by rwaldron** [comment]
Can you split the current `class-fields` into: 

```
- class (already exists)
- class-fields-private
- class-fields-public
```

**Comment by leobalter** [comment]
@gsathya does it work for you? I'm doing this after an indirect request through irc.

**Comment by gsathya** [comment]
`class-fields-private` and `class-fields-public` SGTM, thanks! What would `class` be?

**Comment by rwaldron** [comment]
`class` is because these probably all should've been tagged with `class` to begin with, because it's very likely that some consumer of Test262 will want to run all `class` tests as new `class` features are added. Don't worry though, this isn't a request for extra work from contributors—the maintainers will work to ensure this is completed.

**Comment by gsathya** [comment]
Thanks for the explanation! LGTM.

**Comment by adrianheine** [comment]
Speaking of feature tags, currently all tests tagged `computed-property-names` are about class fields, but some of them are not tagged with `class-fields`.
