### ISSUE TITLE
compareArray is wrong. 

### ISSUE THREAD

**Issue by rwaldron** [tc39/test262#156]
Consider the following: 

```js
compareArray([1, 2, 3], [3, 2, 1]);
```

This will be `true` because the arrays are sorted: 

```js
//-----------------------------------------------------------------------------
function compareArray(aExpected, aActual) {
    if (aActual.length != aExpected.length) {
        return false;
    }

    aExpected.sort();
    aActual.sort();

    var s;
    for (var i = 0; i < aExpected.length; i++) {
        if (aActual[i] !== aExpected[i]) {
            return false;
        }
    }
    return true;
}
```

**Comment by bterlson** [comment]
Can't check at the moment, but do any tests depend on its sorting functionality? I agree this is wonky...

**Comment by rwaldron** [comment]
As it turns out, yes—but not for any valid or relevant semantics.

**Comment by smikes** [comment]
Specifically, the only tests that use `compareArray` at present are

```
test/built-ins/Object/getOwnPropertyNames/15.2.3.4-4-44.js
test/built-ins/Object/getOwnPropertyNames/15.2.3.4-4-49.js
test/built-ins/Object/getOwnPropertyNames/15.2.3.4-4-b-2.js
```

All of them are using `compareArray` to compare an expected set of property names to the result of getOwnPropertyNames.  The tests could easily be changed to apply the sort() directly instead of expecting compareArray() to apply the sort().

@rwaldron do you want to do that or shall I?

**Comment by rwaldron** [comment]
I changed that in the patch already :)

**Comment by smikes** [comment]
The order of property names in getOwnPropertyNames() is implementation-defined, so we still have to sort() in case non-v8 implementations use a different order, right?

**Comment by anba** [comment]
> The order of property names in getOwnPropertyNames() is implementation-defined

For implementations targeting ES5; ES6 has fixed property enumeration order (*).

(*) When using `Object.getOwnPropertyNames`, `Object.getOwnPropertySymbols` or `Reflect.ownKeys`. Property enumeration order is still implementation-defined for `Object.keys` and `for-in`.

**Comment by smikes** [comment]
Ah, thanks. My objection is incorrect then.

**Comment by anba** [comment]
Object/getOwnPropertyNames/15.2.3.4-4-44.js still needs a fix, because the current expected result is V8/SpiderMonkey specific. JavaScriptCore returns `[ "0", "1", "2", "length", "5" ]`. Nashorn returns `[ "0", "1", "2", "5", "length" ]`. And per ES6 (rev33) it should be `[ "0", "1", "2", "5", "length" ]`.

**Comment by rwaldron** [comment]
@anba thanks for the heads up, I'll circle back that

**Comment by rwaldron** [comment]
@anba for those three existing cases, I'm changing them to: 

```js
compareArray(actual.sort(), expected.sort());
```

**Comment by anba** [comment]
Sounds good.

**Comment by jugglinmike** [comment]
@bterlson This was addressed as part of gh-157 and may be closed.
