### ISSUE TITLE
Atomics.wait CanBlockIsFalse

### ISSUE THREAD

**Issue by patrick-soquet** [tc39/test262#1609]
The following test has the `CanBlockIsFalse` flag:

- Atomics/wait/cannot-suspend-throws.js

which seems correct since it is testing if Atomics.wait throws an exception in the main thread. 

But the following tests have also the `CanBlockIsFalse` flag:

- Atomics/wait/false-for-timeout.js
- Atomics/wait/negative-timeout.js
- Atomics/wait/null-for-timeout.js
- Atomics/wait/object-for-timeout.js
- Atomics/wait/true-for-timeout.js

which seems incorrect since they call Atomics.wait in the main thread. Maybe the flag for these tests should be `CanBlockIsTrue`?

Or maybe I misunderstood the specifications? Thank you.

**Comment by rwaldron** [comment]
> The following test has the CanBlockIsFalse flag:
> - Atomics/wait/cannot-suspend-throws.js

Eventually, when we figure out how hosts can "signal" that they are running a test in "main thread, blocking is disallowed", this test will make sense. For now, it will fail on all runtimes that don't need to make that distinction. For those runtimes, it's safe to skip or ignore this test. 


> But the following tests have also the CanBlockIsFalse flag:

Right, because for the time being, `CanBlockIsFalse` is meaningless. It's just there for Test262 maintainers to uniformly identify any tests that will be impacted by whatever comes of the "signal" mechanism I mentioned above.

> Or maybe I misunderstood the specifications? Thank you.

Nope, you're right on. This is actually something I'm hoping to have resolved later this week, I've just been waiting on a review of my large Atomics PR.

**Comment by leobalter** [comment]
This should be fixed in #1617. Please let me know if you find anything else missing. 

Thanks!
