### ISSUE TITLE
Negative tests for parsing phase don't seem to actually detect parsing phase

### ISSUE THREAD

**Issue by mathiasbynens** [tc39/test262#1621]
[Negative tests](https://github.com/tc39/test262/blob/master/CONTRIBUTING.md#negative) are supposed to check for the error to be thrown during the specified `phase`. For early errors, the `phase` would be `parse`, e.g.:

```js
/*---
negative:
  phase: parse
  type: SyntaxError
---*/

/?/;
```

`/?/` is supposed to throw an early error. But, [V8 has a long-standing bug](https://bugs.chromium.org/p/v8/issues/detail?id=896) that causes it throw an error at runtime instead. Still, the test runner thinks everything is good for some reason; the test passes in V8. This seems like a bug.

You can observe the difference by changing the test as follows:

```js
/*---
negative:
  phase: parse
  type: SyntaxError
---*/

if (false) /?/;
```

Now, for V8, you get:

```
Expected test to throw error of type SyntaxError, but did not throw error
```

**Comment by jugglinmike** [comment]
Hey @mathiasbynens! We tried to address this in gh-1073 (and actually, the bug in
V8 was one of the motivations). By throwing a string literal in negative syntax
tests, we allow consumers a means to differentiate between runtime and parsing
errors. As part of that patch, we implemented a linting rule so that future
contributions would consistently include a `throw` statement (which we found
preferable  to an interpreting guideline like, "Please modify negative syntax
tests with a `throw` statement prior to evaluation")

Here's an example:

https://github.com/tc39/test262/blob/e9a5a7f918c0f9c4a9f1224d25a6d55147953225/test/language/literals/regexp/invalid-braced-quantifier-lower.js

This means that the first example you shared shouldn't be allowed by our
continuous integration system and shouldn't be in Test262 at all. That said, we
may have mistakenly accepted tests that violate the linting rule, or we may
have missed updating legacy tests when we introduced it. Let me know if that's
the case, and I'll fix the tests post-haste.

This may also be a problem if consumers don't validate the *type* of error
thrown as described in the interpreting guidelines. For instance, a consumer
that simply checks that "some error was thrown" by a negative syntax test would
pass that example above even if it evaluated the code.

It's always possible that I am laughably wrong about some basic and
obvious truth. I'd welcome any feedback along these lines, though I might need
to sit down, first.

**Comment by littledan** [comment]
Thanks for the response, @jugglinmike . For V8, this needs work on V8's harness to put things together. I was hoping to do this myself, but haven't had the time. @mathiasbynens If you'd like to fix this issue in V8's test setup, I'd be happy to walk you through how to do it.

**Comment by mathiasbynens** [comment]
Thanks for the background that I was missing, @jugglinmike, and for linking to an example. I now realize that this `throw` requirement is also documented here: https://github.com/tc39/test262/blob/master/CONTRIBUTING.md#handling-errors-and-negative-test-cases My bad!

@littledan I would like to fix this indeed. Please let me know what you had in mind.

**Comment by mathiasbynens** [comment]
Looks like https://github.com/tc39/test262/blob/e9a5a7f918c0f9c4a9f1224d25a6d55147953225/tools/lint/lib/checks/negative.py#L5 enforces this exact source string to be part of negative tests:

```
throw "Test262: This statement should not be evaluated.";
```

That's great! A hacky workaround for V8's test runner wcould be to remove these lines before running the test.

**Comment by mathiasbynens** [comment]
Closing as this is working as intended.

**Comment by jugglinmike** [comment]
Happy to help!
