### ISSUE TITLE
Assert messages?

### ISSUE THREAD

**Issue by arv** [tc39/test262#192]
In https://github.com/tc39/test262/pull/183#issuecomment-77258097 @bterlson commented that the test was lacking assertion messages. It is not clear that passing messages to the assert functions is valuable. We already have a description of the test in the meta data. Adding human readable messages in the assert functions have high overhead an very low value. Once you get a test failure you still need to look at the test to figure out what is failing.

@rossberg-chromium, @rwaldron @jugglinmike

**Comment by bterlson** [comment]
I would agree with you if tests had very minimal number of assertions, but they don't, many of the new tests we're adding have many assertions. I find the messages to be a big help in locating the line to investigate. Yes at that point you have to go understand the test, but just knowing where to start looking seems helpful.

I'm sympathetic to concerns about the time it takes to add the error messages. If it's too much overhead I can be convinced it's not required. But "very low value" runs counter to my experience in dealing with failures in tests with multiple assertions.

Curious what other test262 consumers might think, if they want to chime in (@smikes?)

**Comment by rwaldron** [comment]
A few tangentially related thoughts, none of which I've spent the time to investigate, so consider this a list of "Things I Will Look Into".

- Is it possible to update the test runner so that it outputs the line number? 
- Can we remove certain test runner output?
  - Specifically, this part: 

  ```
  --- output ---
  /var/folders/jl/3l91m2l97xjbh10v99_xmwmh0000gn/T/test262-w3N9nc.js:17: 
  ```
  of: 
  ```
  === built-ins/Symbol/collection/disallowed-as-weakmap-key failed in non-strict mode ===
  --- output ---
   /var/folders/jl/3l91m2l97xjbh10v99_xmwmh0000gn/T/test262-w3N9nc.js:17: Test262Error: Expected a TypeError to be thrown but no exception was thrown at all
      throw new Test262Error(message);
            ^===
  ```  
  That specific data has yet to be useful to me (if others have use cases, please share) and clutters the terminal with unnecessary characters. (Note the actual file: `/var/folders/jl/3l91m2l97xjbh10v99_xmwmh0000gn/T/test262-w3N9nc.js` is empty)

  More useful: 

  ```
  === built-ins/Symbol/collection/disallowed-as-weakmap-key failed in non-strict mode ===
  Line: [[Line Number]]

  Test262Error: Expected a TypeError to be thrown but no exception was thrown at all
      throw new Test262Error(message);
            ^===
  ```  
  - Is this better fulfilled by an alternate reporter?

**Comment by rossberg-chromium** [comment]
On 18 March 2015 at 00:59, Brian Terlson <notifications@github.com> wrote:

> I would agree with you if tests had very minimal number of assertions, but
> they don't, many of the new tests we're adding have many assertions. I find
> the messages to be a big help in locating the line to investigate. Yes at
> that point you have to go understand the test, but just knowing where to
> start looking seems helpful.
>
> I'm sympathetic to concerns about the time it takes to add the error
> messages. If it's too much overhead I can be convinced it's not required.
> But "very low value" runs counter to my experience in dealing with failures
> in tests with multiple assertions.
>
> Curious what other test262 consumers might think, if they want to chime in
> (@smikes <https://github.com/smikes>?)
>

I don't mind the output, but personally, I never had any use for it (nor
anybody else around here, AFAICT).

Ultimately it comes down to cost. Requiring every assertion failure to
self-identify probably doubles the amount of work for every simple test.
And there are many, many new tests we need for ES6. Given that resources
are severely limited (and I don't foresee this changing), it seems wasteful
to require spending half of them on a detail that is only marginally useful.

Doing this programmatically seems to be the wrong level of abstraction,
too. The test already have a lot of meta-data. The test runner should be
able to mine that, plus display line numbers as Rick suggested.

/Andreas

**Comment by bterlson** [comment]
> Is it possible to update the test runner so that it outputs the line number? 

Test262-harness displays line numbers for thrown errors, but $ERROR does not throw an error. Is the proposal that $ERROR should throw? I was hoping to avoid this so I could keep running the test and report multiple errors. And then the harness needs to display the whole stack because the top frames might be in assertion helpers.

> Can we remove certain test runner output?

Do what you will with the python harness, but yes, I think a new reporter would be a good place to start...

> Given that resources are severely limited (and I don't foresee this changing), it seems wasteful to require spending half of them on a detail that is only marginally useful.

Ok, we can forego, assuming we can figure out how to report line numbers.
