### ISSUE TITLE
Identifier tests

### ISSUE THREAD

**Issue by mathiasbynens** [tc39/test262#193]
I’d like to contribute [my ES6 identifier tests](https://mathias.html5.org/tests/javascript/identifiers/) to test262. Currently there are some tests in https://github.com/tc39/test262/tree/master/test/language/identifiers. 

What format would you like me to use? Should there be a separate file per individual test (i.e. per identifier)? (That would mean adding thousands of files.)

**Comment by smikes** [comment]
No, thousands of files would not be good.

To summarize the structure: there is a file `symbols.js` that defines two arrays `identifierStart` and `identifierPart` which are legal initial and medial identifier characters.  This file is 679kb.

There is a data section where special cases (e.g., `eval`) are set up.

There is a driver which generates functions of the form
```
Function("var " + identifier)
``` 

The driver iterates over all the special cases; over each the `identifierStart` characters; and over `_` followed by each of the `identifierPart` characters.

I think it would be best to build a few tests.  The `data` section of special cases and the driver can form one test.  

Rather than testing `identifierStart` and `identifierPart` dynamically, though, I'd rather see:

```
var a
var b
var c
//... etc
```

But not all as one file: breaking them into files of about a hundred kb each.

@bterlson , @anba any comments?

**Comment by bterlson** [comment]
There are tests for identifiers somewhere that have a quad-nested for loop and test every combination of identifiers. I believe. I will try to find. But I like @smikes' suggestion anyway.

**Comment by leobalter** [comment]
I believe this is reasonably covered by now, please reopen if necessary.
