### ISSUE TITLE
Missing private field access on object destructuring

### ISSUE THREAD

**Issue by caiolima** [tc39/test262#2072]
It needs to throw a SyntaxError:

```
class Foo {
    #x = 1;
    destructureX() {
        const { #x: x } = this;
        return x;
    }
}
```

**Comment by leobalter** [comment]
This is as invalid as there is no grammar for `#name` alone beyond the class elements list. We just have to be careful to avoid all the other places this doesn’t apply to. 

The test should also tell clearly the production is a syntax error not because a direct syntactical parsing directive, but the lack of any production from the specs.

If you’re interested to add this, I believe it’s best to avoid spreading to other different cases, e.g. other dstr positions or we would have too many tests

**Comment by caiolima** [comment]
> The test should also tell clearly the production is a syntax error not because a direct syntactical parsing directive, but the lack of any production from the specs.

Ok. BTW, the motivation to add such test is because of the following issue: https://bugs.chromium.org/p/v8/issues/detail?id=8808
