### ISSUE TITLE
Missing coverage for Object.defineProperty method

### ISSUE THREAD

**Issue by NWU-NISL** [tc39/test262#2660]
Testcase:

When redefining the "length" property, a non-configurable property of an Array object and set its value to be true, JS engines should throw TypeError. After careful inspection, I found that there is no similar testcase to test the above behavior. The testcase for sort of like this:

```
var NISLFuzzingFunc = function(){
	var arrobj = [0, 1];
	Object.defineProperty(arrobj, "length", {
		value: 1,
		configurable: true
	});
};
NISLFuzzingFunc();
```

By the way, the above testcase triggered a [bug](https://bugs.chromium.org/p/v8/issues/detail?id=9460) of Google V8. Also, there is a similar testcase that triggered a [bug](https://bugs.webkit.org/show_bug.cgi?id=203456) of JavaScriptCore.

**Comment by rwaldron** [comment]
The semantics described are covered here: https://github.com/tc39/test262/blob/main/test/built-ins/Object/defineProperty/15.2.3.6-4-120.js

But what's peculiar is that this test was passing before the fix to V8: https://test262.report/browse/built-ins/Object/defineProperty/15.2.3.6-4-120.js?date=2019-07-01. So I looked at the change and the tests written for the change, and then looking at your test I realized that V8 was allowing that code to execute because only because the new length value was not greater than the old length value (https://chromium.googlesource.com/v8/v8.git/+blame/40624b5b41b775e52ff165d2cd8fd060fdcfdf8d/src/objects/objects.cc#3273), and by default array length is `writable: true`, which meant it missed the original condition here: https://chromium.googlesource.com/v8/v8.git/+/40624b5b41b775e52ff165d2cd8fd060fdcfdf8d%5E%21/src/objects/objects.cc, where new desc `configurable: true` wasn't being guarded against. I'm not sure that counts as "missing coverage", considering Test262 had tests for all of those things in isolation.
