### ISSUE TITLE
An interesting test case related to the eval method

### ISSUE THREAD

**Issue by NWU-NISL** [tc39/test262#2814]
**Description:**

Test262 may miss the test case where the argument name of a function is `eval`, like the following example:

```js
var NISLFuzzingFunc = function(eval){
    print(eval("print(false);"));
};
var NISLParameter1 = function(){
    print("run to NISLParameter1");
    return true;
};
NISLFuzzingFunc(NISLParameter1);
```

The test case triggered a bug of the QuickJS engine which treats the local variable `eval` as the API function call of JS engine.

**QuickJS Version:**

quickjs-2019-09-01

**QuickJS Output:**

```js
false
undefined
```

**Expected Output:**

```js
run to NISLParameter1
true
```

**Comment by rwaldron** [comment]
I'm not sure what the issue is? There is certainly a bug in QuickJS, but Test262 has this covered: 

- `eval` is allowed as the name of a formal parameter in **non-strict code**: 
  - https://github.com/tc39/test262/blob/main/test/language/expressions/function/param-eval-non-strict.js
  - https://github.com/tc39/test262/blob/main/test/language/statements/function/param-eval-non-strict.js
- `eval` is _not_ allowed as the name of a formal parameter in **strict code**: 
  - https://github.com/tc39/test262/blob/main/test/language/expressions/function/param-eval-non-strict.js
  - https://github.com/tc39/test262/blob/main/test/language/statements/function/param-eval-strict.js
