### ISSUE TITLE
Missing tests for `for await (async of`

### ISSUE THREAD

**Issue by Zalathar** [tc39/test262#2979]
It was recently noticed (https://github.com/babel/babel/issues/13235) that Babel failed to parse this code:

```js
async function f() {
    for await (async of []);
}
```

Unlike a regular for-of loop there is no ambiguity with `for (async of => {};;)`, and an async function expression is not legal here, so `async` can be used as the loop variable.

But it's easy for the implementation to mess up by parsing `async of` as an async function anyway, or by incorrectly sharing code that prohibits `for (async of` in a regular for-of.

**Comment by jugglinmike** [comment]
That sounds like a meaningful test case to me. Thanks for the report!

Would you like to write the test? I'm available to help you get started if you need a hand.

**Comment by Zalathar** [comment]
I was able to write some test cases based on the existing templates in `src/dstr-binding-for-await/default/`, but I'm a bit lost on where to put them (since they aren't destructuring?) or what documentation they need.

I guess I should just submit a draft PR with what I have so far?

**Comment by jugglinmike** [comment]
Great! I'm happy to give feedback on a work-in-progress.

Since this issue is orthogonal to the parsing of destructuring patterns, using those templates may produce a lot of tests which aren't meaningfully distinctive for implementers. This sounds like a case for hand-written tests, but we can discuss that in the context of your patch if you prefer.

**Comment by bakkot** [comment]
The [PR which added tests for other cases](https://github.com/tc39/test262/pull/2935/files) may be useful context.
