### ISSUE TITLE
built-ins/TypedArray/prototype/copyWithin/return-abrupt-from-this-out-of-bounds.js is misleading

### ISSUE THREAD

**Issue by marjakh** [tc39/test262#3207]
It does this (3 times):

array.copyWithin(new TA(), 0);

The first parameter of copyWithin is supposed to be the target index, but this test is passing a TypedArray object. It only works because the TA is converted to the number 0. This is pretty misleading and probably unintentional.

cc @jugglinmike

**Comment by jugglinmike** [comment]
Thanks for the report! That was definitely a mistake on my part. Here's a fix: gh-3215.

As it turns out, while Test262 already has tests for the type coercion of that argument, it doesn't verify an object value specifically. That's why in addition to replacing `new TA()` with `0` for these tests intended to verify the Resizable ArrayBuffer proposal, I've also added a few assertions to the tests for the coercion of object values.
