### ISSUE TITLE
Need Annex B tests

### ISSUE THREAD

**Issue by bterlson** [tc39/test262#33]
Can feature detect browsers by checking for Annex B FIB behavior.

**Comment by bakkot** [comment]
It looks to me like annex B is mostly tested, but a few things aren't done:
- [ ] B.1.1
- [ ] B.1.2
- [ ] B.1.3
- [ ] B.3.1 (partially complete)
- [ ] B.3.3
- [ ] B.3.4

**Comment by bakkot** [comment]
Here's a few of functions which demonstrate B.3.3's effect as I understand it (or rather the intended effect, keeping in mind that the current version of the spec [has a bug](https://bugs.ecmascript.org/show_bug.cgi?id=4427)). I'm including them here instead of in a PR because I'm not sure what format tests are currently supposed to have and so that people can confirm my understanding of spec.
```javascript
(function(){
  var g;
  function getOuterVar(){
    return f;
  }

  {
    g = f;
    function f(){}
  }
  return typeof g;
}()); // returns 'function'

(function(){
  var g;
  function getOuterVar(){
    return f;
  }

  {
    g = getOuterVar();
    function f(){}
  }
  return typeof g;
}()); // returns 'undefined'

(function(){
  var g;
  function getOuterVar(){
    return f;
  }

  {
    function f(){}
    g = getOuterVar();
  }
  return typeof g;
}()); // returns 'function'

(function(){
  var g;
  function getOuterVar(){
    return f;
  }

  {
    f = 1;
    g = getOuterVar();
    function f(){}
  }
  return typeof g;
}()); // returns 'undefined'

(function(){
  var g;
  function getOuterVar(){
    return f;
  }

  {
    f = 1;
    function f(){}
    g = getOuterVar();
  }
  return typeof g;
}()); // returns 'number'
```

**Comment by domenic** [comment]
I think @littledan probably has some good V8 tests that could be converted

**Comment by leobalter** [comment]
We've got this covered in the last year.
