### ISSUE TITLE
Add tests for AggregateError constructor with non-iterable `errors` argument

### ISSUE THREAD

**Issue by camnwalter** [tc39/test262#4219]
When calling AggregateError's constructor, if the `errors` argument is not iterable, a TypeError should be thrown.

See https://tc39.es/ecma262/#sec-aggregate-error and https://tc39.es/ecma262/#sec-getiterator

**Comment by ljharb** [comment]
Isn't that covered by https://github.com/tc39/test262/blob/d9b10790bc4bb5b3e1aa895f11cbd2d31a5ec743/test/built-ins/NativeErrors/AggregateError/errors-iterabletolist-failures.js and https://github.com/tc39/test262/blob/d9b10790bc4bb5b3e1aa895f11cbd2d31a5ec743/test/built-ins/NativeErrors/AggregateError/errors-iterabletolist.js ?

**Comment by ljharb** [comment]
i do see that the tests only cover a noniterable object, and it's fine to add more cases to cover that, but i'm having trouble understanding how you'd have implemented it following the spec and caused undefined/absent or numbers to not fail, since everything should be using the equivalent of `GetIterator()`.

**Comment by camnwalter** [comment]
Ok never mind, that was an issue with my implementation, but I think it still would be good to add an empty arguments test.

**Comment by ljharb** [comment]
oh sure, if any implementation including yours ran into it, we should be covering it :-)

i was more just curious how you'd implemented it that you ran into that problem.

**Comment by camnwalter** [comment]
I had a check for the argument length but if it wasn't >= 1 I didn't do anything 😭

**Comment by p-bakker** [comment]
To add to the above (which comes from Rhino): the tests expect a TypeError. For us the tests gives a false positive, as it does throw a TypeError, but (incorrectly so) on the {get [Symbol.xxx]() {}} syntax. 

So I'm looking into whether there are any tests for that scenario, which I think ought to be in /language/expressions/object/accessor-name-computed-*, but am not seeing anything in there related to using a Symbol as key

Might this be missing, or am I looking in the wrong location?

**Comment by ljharb** [comment]
The fact that it's a symbol is irrelevant to the syntax, it's `get [<expression>]`.

Anything that assigns a Symbol key should cover whether symbols can be keys.

**Comment by p-bakker** [comment]
Well, I agree that the accessor syntax in Objects for computed properties itself doesn't care about whether the key is a symbol of not, but I'm saying there's no test that covers that scenario

There is a test for method definitions using a Symbol, see https://github.com/tc39/test262/blob/main/test/language/computed-property-names/object/method/symbol.js

But there's no test for an accessor using a symbol: https://github.com/tc39/test262/tree/main/test/language/computed-property-names/object/accessor/*

For language/computed-property-names/object/method there are tests for all primitives, but not so for language/computed-property-names/object/accessors

Due to that, our faulty implementation of method accessors using computed property names based on Symbols didn't surface and hence we got false positives while testing AggregateErrors.

Should /language/computed-property-names/object/accessor/ contain tests for all primitives?

**Comment by ljharb** [comment]
That seems like a good idea, yeah

**Comment by p-bakker** [comment]
Would it be OK to put tests for string/number/symbol accessors all into [getter.js](https://github.com/p-bakker/test262/blob/4219_add_tests/test/language/computed-property-names/object/accessor/getter.js) & [setter.js](https://github.com/p-bakker/test262/blob/4219_add_tests/test/language/computed-property-names/object/accessor/setter.js)? Or would they have to be split out into individual files?

**Comment by ljharb** [comment]
I think it'd be fine to add a few more kinds of cases to those existing files.

**Comment by p-bakker** [comment]
Created a PR with the discussed tests
