### ISSUE TITLE
ESMeta CI job is failing

### ISSUE THREAD

**Issue by ptomato** [tc39/test262#4267]
Since a couple of days ago, the ESMeta CI job is failing because it cannot locate the `sbt` binary.

**Comment by ptomato** [comment]
cc @doehyunbaek @jhnaldo - any idea what is happening?

**Comment by ptomato** [comment]
See https://github.com/actions/runner-images/issues/10788 and https://github.com/actions/runner-images/issues/10636

**Comment by jhnaldo** [comment]
Thanks for letting me know the problem.

> See [actions/runner-images#10788](https://github.com/actions/runner-images/issues/10788) and [actions/runner-images#10636](https://github.com/actions/runner-images/issues/10636)

This issue seems the main reason for the problem.

Should we wait until this issue is resolved in `actions`, or should we try to resolve this issue now?

**Comment by ljharb** [comment]
What would probably be wisest is to add a step to https://github.com/tc39/test262/blob/main/.github/workflows/esmeta-test262.yml (and https://github.com/tc39/ecma262/blob/main/.github/workflows/esmeta-typecheck.yml) that installs `sbt`, that's skipped if it's already present. That way, if github fixes it, the job will be faster, but it'll work regardless.

Additionally, it'd probably be good to create a single esmeta action that both of these workflows can use, so that there's only one place needed to change for stuff like this.

**Comment by ptomato** [comment]
https://github.com/tc39/test262/pull/4270 should fix it. It doesn't skip installing SBT if already present, but I think it's pretty unlikely that GitHub would re-add it, given that people have been complaining for three weeks already.
