### ISSUE TITLE
Missing promise coverage

### ISSUE THREAD

**Issue by domenic** [tc39/test262#443]
V8 has a number of subtle promise bugs which @littledan and I are reasonably sure are not caught by test262 tests. (We have most test262 tests on for promises, and the ones we have disabled don't seem like they would catch these bugs.)
- https://code.google.com/p/v8/issues/detail?id=4162
- https://code.google.com/p/v8/issues/detail?id=3641
- https://code.google.com/p/v8/issues/detail?id=4539

It would be good to not only add tests to catch these bugs, but also do a bit of investigation to see which parts of the spec these bugs stress, and why test262's fairly-exhaustive coverage misses them. That might reveal a few other potentially missing tests or V8 bugs.

**Comment by anba** [comment]
Just added #445 which covers built-in function tests, IIRC V8 does not pass the "*-function-nonconstructor.js" tests.

**Comment by anba** [comment]
#447 adds more Promise tests, including a few which don't pass in current V8.

**Comment by jugglinmike** [comment]
@domenic Following up on @anba's contribution, we further expanded test coverage
for Promises in gh-461, gh-462, gh-463, gh-464, and gh-465 based on an analysis
of the abstract operations. Here's a diagram that, despite all appearances, was
authored by a grown man:

![promise-state-machine](https://cloud.githubusercontent.com/assets/677252/12960045/24f20ec6-d007-11e5-8e9f-79be200e8c62.jpg)

Because of the amount of re-use in abstract operations, the Promise test suite
now has a fair number of closely-related tests.

[v8/4162](https://bugs.chromium.org/p/v8/issues/detail?id=4162) Describes a failure to observe two distinct behaviors:

1. accessing the `then` property of an object-coercible resolution value
2. invoking such a method if it exists

In the first case, we are asserting the property access (along with the
handling of resulting abrupt completions) with the following tests:

- [Promise/resolve-poisoned-then-immed.js](https://github.com/tc39/test262/blob/5cb97c293b4a44ee1c31961a07663993c521fb5f/test/built-ins/Promise/resolve-poisoned-then-immed.js)
- [Promise/resolve-poisoned-then-deferred.js](https://github.com/tc39/test262/blob/5cb97c293b4a44ee1c31961a07663993c521fb5f/test/built-ins/Promise/resolve-poisoned-then-deferred.js) (this matches the reported case)
- [Promise/all/resolve-poisoned-then.js](https://github.com/tc39/test262/blob/5cb97c293b4a44ee1c31961a07663993c521fb5f/test/built-ins/Promise/all/resolve-poisoned-then.js) (one of the stranger tests I've written)
- [Promise/prototype/then/resolve-pending-fulfilled-poisoned-then.js](https://github.com/tc39/test262/blob/5cb97c293b4a44ee1c31961a07663993c521fb5f/test/built-ins/Promise/prototype/then/resolve-pending-fulfilled-poisoned-then.js)
- [Promise/prototype/then/resolve-pending-rejected-poisoned-then.js](https://github.com/tc39/test262/blob/5cb97c293b4a44ee1c31961a07663993c521fb5f/test/built-ins/Promise/prototype/then/resolve-pending-rejected-poisoned-then.js)
- [Promise/prototype/then/resolve-settled-fulfilled-poisoned-then.js](https://github.com/tc39/test262/blob/5cb97c293b4a44ee1c31961a07663993c521fb5f/test/built-ins/Promise/prototype/then/resolve-settled-fulfilled-poisoned-then.js)
- [Promise/prototype/then/resolve-settled-rejected-poisoned-then.js](https://github.com/tc39/test262/blob/5cb97c293b4a44ee1c31961a07663993c521fb5f/test/built-ins/Promise/prototype/then/resolve-settled-rejected-poisoned-then.js)
- [Promise/race/resolve-poisoned-then.js](https://github.com/tc39/test262/blob/5cb97c293b4a44ee1c31961a07663993c521fb5f/test/built-ins/Promise/race/resolve-poisoned-then.js)
- [Promise/resolve/resolve-poisoned-then.js](https://github.com/tc39/test262/blob/5cb97c293b4a44ee1c31961a07663993c521fb5f/test/built-ins/Promise/resolve/resolve-poisoned-then.js)

For the second case, we now have corresponding tests that resolve with "plain"
thenables:

- [Promise/resolve-thenable-immed.js](https://github.com/tc39/test262/blob/5cb97c293b4a44ee1c31961a07663993c521fb5f/test/built-ins/Promise/resolve-thenable-immed.js)
- [Promise/resolve-thenable-deferred.js](https://github.com/tc39/test262/blob/5cb97c293b4a44ee1c31961a07663993c521fb5f/test/built-ins/Promise/resolve-thenable-deferred.js) (this matches the reported case)
- [Promise/all/resolve-thenable.js](https://github.com/tc39/test262/blob/5cb97c293b4a44ee1c31961a07663993c521fb5f/test/built-ins/Promise/all/resolve-thenable.js)
- [Promise/prototype/then/resolve-pending-fulfilled-thenable.js](https://github.com/tc39/test262/blob/5cb97c293b4a44ee1c31961a07663993c521fb5f/test/built-ins/Promise/prototype/then/resolve-pending-fulfilled-thenable.js)
- [Promise/prototype/then/resolve-pending-rejected-thenable.js](https://github.com/tc39/test262/blob/5cb97c293b4a44ee1c31961a07663993c521fb5f/test/built-ins/Promise/prototype/then/resolve-pending-rejected-thenable.js)
- [Promise/prototype/then/resolve-settled-fulfilled-thenable.js](https://github.com/tc39/test262/blob/5cb97c293b4a44ee1c31961a07663993c521fb5f/test/built-ins/Promise/prototype/then/resolve-settled-fulfilled-thenable.js)
- [Promise/prototype/then/resolve-settled-rejected-thenable.js](https://github.com/tc39/test262/blob/5cb97c293b4a44ee1c31961a07663993c521fb5f/test/built-ins/Promise/prototype/then/resolve-settled-rejected-thenable.js)
- [Promise/race/resolve-thenable.js](https://github.com/tc39/test262/blob/5cb97c293b4a44ee1c31961a07663993c521fb5f/test/built-ins/Promise/race/resolve-thenable.js)
- [Promise/resolve/resolve-thenable.js](https://github.com/tc39/test262/blob/5cb97c293b4a44ee1c31961a07663993c521fb5f/test/built-ins/Promise/resolve/resolve-thenable.js)

The other two bugs were *not* addressed by those recent additions.

[v8/3641](https://bugs.chromium.org/p/v8/issues/detail?id=3641) boils down to a faulty optimization. I've submitted gh-500 to cover that in the various places it can be observed.

Luckily, [v8/4539](https://bugs.chromium.org/p/v8/issues/detail?id=4539) concerns the semantics of `Promise.prototype.then` specifically, so that can be
covered with a single test--see gh-501.

**Comment by domenic** [comment]
This is great stuff! Love the diagram :). So, do you feel that after the added tests most/all of the branches of the diagram are covered?

**Comment by jugglinmike** [comment]
Thanks! Yes, all branches are covered. Although the files are of course organized by API method, I structured my commits according to the abstract operations. Here's a summary--there is a test file for every "spec branch"/"observable from" pair:

- PerformPromiseThen
  - Spec: [25.4.5.3.1 PerformPromiseThen](http://www.ecma-international.org/ecma-262/6.0/#sec-performpromisethen)
  - git commits: https://github.com/tc39/test262/commit/a5bf19486a6e5a58193580c088fb715baa57f90e, https://github.com/tc39/test262/commit/f01767916ab7b10b7dc3ec55583101f2056055f5
  - Spec branches:
    - With a fulfilled promise (`prfm-fulfilled.js`)
    - With a rejected promise (`prfm-rejected.js`)
    - With a pending promise that is later fulfilled (`prfm-pending-fulfilled.js`)
    - With a pending promise that is later rejected (`prfm-pending-rejected.js`)
  - Observable from
    - `Promise.prototype.then`
- PromiseResolveFunctions
  - Spec: [25.4.1.3.2 Promise Resolve
    Functions](http://www.ecma-international.org/ecma-262/6.0/#sec-promise-resolve-functions)
  - git commits: https://github.com/tc39/test262/commit/b1b4f04494fa15ecca154805c9422a42c447b1c4
  - Spec branches
    - To PromiseResolveThenableJob (when resolving with a thenable object)
      - `resolve-*-thenable`
      - `resolve-*-prms-cstm-then` (not yet landed; proposed in gh-500)
    - To FulfillPromise (when resolving with a primitive or non-thenable object)
      - `resolve-*-non-object`
      - `resolve-*-non-thenable`
    - To RejectPromise (when resolving with the same promise instance, or when
      GET(resolution, "then") fails
      - `resolve-*-self`
      - `resolve-*-poisoned-then`
  - Observable from
    - `Promise` (testing immediate resolution from within the executor function
       and "deferred" execution to some point after construction)
      - `resolve-*-deferred.js`
      - `resolve-*-immed.js`
    - `Promise.resolve`
    - `Promise.race`
    - `Promise.all`
    - `Promise.prototype.then` (testing through PerformPromiseThen, which
      expands the branch points a bit)
      - `resolve-settled-fulfilled-*`
      - `resolve-settled-rejected-*`
      - `resolve-pending-fulfilled-*`
      - `resolve-pending-rejected-*`
- PerformPromiseAll
  - Spec: [25.4.4.1.1 Runtime Semantics:
    PerformPromiseAll](http://www.ecma-international.org/ecma-262/6.0/#sec-performpromiseall)
  - git commits: https://github.com/tc39/test262/commit/bb26beece201efdc42e6883c533ffe71646f641f, https://github.com/tc39/test262/commit/b1b4f04494fa15ecca154805c9422a42c447b1c4, https://github.com/tc39/test262/commit/7fab70bb21c4f1c676372e4a525e71d1df018e5d
  - Spec branches
    - All promises fulfilled (`resolve-*`)
    - Any promise rejected (`reject-*`)
  - Observable from 
    - `Promise.all`
- PerformPromiseRace
  - Spec: [25.4.4.3.1 Runtime Semantics:
    PerformPromiseRace](http://www.ecma-international.org/ecma-262/6.0/#sec-performpromiserace)
  - git commits: https://github.com/tc39/test262/commit/6e9d88a293ec123c0a3856ed8d1a597a3ffd7cd9, https://github.com/tc39/test262/commit/b1b4f04494fa15ecca154805c9422a42c447b1c4, https://github.com/tc39/test262/commit/7fab70bb21c4f1c676372e4a525e71d1df018e5d
  - Spec branches
    - Any promise fulfilled (`resolve-*`)
    - Any promise rejected (`reject-*`)
  - Observable from
    - `Promise.race`

Some abstract operations do not branch internally. These are still tested in full, but coverage is a little easier to verify because it only concerns from where the operation is observable. For example, PromiseRejectFunction is observable from `Promise`, `Promise.reject`, `Promise.all`, `Promise.race`, and `Promise.prototype.then`--commit here:  https://github.com/tc39/test262/commit/7fab70bb21c4f1c676372e4a525e71d1df018e5d

I'm eliding details about branches between built-in APIs and user code, as the treatment there is much more straightforward. For instance, because PerformPromiseRace invokes `Promise.prototype.then`, it technically relies on PerformPromiseThen. That means the diagram implies a lot more branching.  In cases where the spec calls back out to the built-in API, I simply wrote tests for the Call invocation, taking for granted that each API is well-tested elsewhere (e.g. [Promise/race/invoke-then.js](https://github.com/tc39/test262/blob/5cb97c293b4a44ee1c31961a07663993c521fb5f/test/built-ins/Promise/race/invoke-then.js) and [Promise/race/invoke-then-error.js](https://github.com/tc39/test262/blob/5cb97c293b4a44ee1c31961a07663993c521fb5f/test/built-ins/Promise/race/invoke-then-error.js)). This is also why `Promise.prototype.catch` is not mentioned anywhere above; that method is [particularly easy to test](https://github.com/tc39/test262/tree/5cb97c293b4a44ee1c31961a07663993c521fb5f/test/built-ins/Promise/prototype/catch) if you take the correct behavior of `Promise.prototype.then` for granted.

**Comment by rwaldron** [comment]
@jugglinmike @domenic @anba @littledan ping for status (of any kind)

**Comment by jugglinmike** [comment]
No status update. I'd appreciate a second opinion about the completeness of my work.

**Comment by littledan** [comment]
I'm sorry, but it's a lot of work to evaluate the completeness of tests and I'm not able to do it right now. I appreciate the outline above and the tests that you added that recently landed; none of them failed in V8 when I did the roll.

**Comment by leobalter** [comment]
From my perspective I can't find coverage gaps or any other edge cases we could add. After the audit all the good work you did and documented very well, I believe it's good we move on celebrating these tests.

At this point, the time we have available for maintenance makes it worth relying on eventual bug reports if any appears - I guess they won't - to improve coverage.

This documentation is also good to have in mind for the upcoming tests for new Promise features, I believe @ljharb will enjoy it.
