### ISSUE TITLE
Reuse harness `testWithTypedArrayConstructors` on TypedArray constructor methods

### ISSUE THREAD

**Issue by leobalter** [tc39/test262#478]
As a have a work in progress on the TypedArray constructors, I would like to know what's best in the PoV of who implements the feature:

1. Write a single file for all the constructors, using the harness `testWithTypedArrayConstructors` function on a test for the same spec step.
2. Isolate each test for each kind of constructor.

Examples:

```js
// Case 1
// test/built-in/TypedArrays/length-is-undefined-throws.js
/*---
description: >
  If length is undefined, throw a TypeError exception.
info: >
  22.2.4.2 TypedArray ( length )

  This description applies only if the TypedArray function is called with at
  least one argument and the Type of the first argument is not Object.

  ...
  3. If length is undefined, throw a TypeError exception.
  ...
includes: [testTypedArray.js]
---*/

testWithTypedArrayConstructors(function(TA) {
  assert.throws(TypeError, function() {
    new TA(undefined);
  });
});
```

or

```js
// Case 2:
// test/built-in/TypedArrays/Float32Array/length-is-undefined-throws.js
/*---
description: >
  If length is undefined, throw a TypeError exception.
info: >
  22.2.4.2 TypedArray ( length )

  This description applies only if the TypedArray function is called with at
  least one argument and the Type of the first argument is not Object.

  ...
  3. If length is undefined, throw a TypeError exception.
  ...
includes: [testTypedArray.js]
---*/

assert.throws(TypeError, function() {
  new Float32Array(undefined);
});

// Plus a new file for Float64Array, Int8Array, Int16Array, ...
```

On the first case we would certainly have a cleaner files structure, my only concern is how it is useful when someone has started implementing TypedArrays and don't have all of them defined. A single file testing them all are not helpful for this progress, as any error will prevent the tests to continue on that file.

On the other side, the second case requires extra maintenance if something changes. At least if gives the perfect location where the error happened.

My preference is on case 2, even if it multiplies the files by 9x. It's more clear to see what is happening if we don't omit the main object being tested on a local variable.

**Comment by jugglinmike** [comment]
Good point, Leo. As you know, we've been discussing the possibility of procedural test generation for a little while now. Since duplication for Typed Arrays can be addressed naturally (using the `testWithTypedArrayConstructors` helper as you've demonstrated), I've mostly ignored them in that discussion.

The use-case of partial implementations makes file generation seem more relevant. By essentially using `testWithTypedArrayConstructors` to build static files, we'd give implementors more control. This would also make failures easier to diagnose in addition to addressing the readability concerns you raised.

The good news is: the system we've been designing in gh-470 will certainly support generating test files like the one you've described in option 2.

That said, the tool doesn't exist yet, and you want to write tests today! My advice would be to use the `testWithTypedArrayConstructors` helper for now. It may not be optimal for all implementors, but:

1. Code review will be easier (we'll have 1/9th as many files to look through)
2. A sub-optimal solution is better than no solution, provided we agree that
   it is temporary!
3. I expect that most implementors will use internal abstractions to define the
   Typed Array API, so it may not be very likely that someone has (for example)
   `Uint8Array` "almost done" without anything defined for `Float26Array`

**Comment by leobalter** [comment]
I like the advantages you pointed, @jugglinmike. I'll follow it.

I'll close this issue to prevent noise on others, I believe the interaction case - from now - will be best reviewed when I open a PR with it.
