### ISSUE TITLE
Coverage: B.3.3 with nested blocks

### ISSUE THREAD

**Issue by bakkot** [tc39/test262#697]
As far as I can tell, test262 isn't checking anything like

```js
(function () {
  {
    let f = 2;
    {
      function f() {}
    }
  }
  return typeof f == 'undefined'; // true
})()
```

In this case there is no hoisting of f, because replacing it with `var f` would cause an early error (in particular a conflict with the `let`).

V8 and JavaScriptCore both fail this test (or at least have failed it in the recent past).

**Comment by littledan** [comment]
There are a bunch more tests available at https://codereview.chromium.org/2099623003/diff/40001/test/mjsunit/es6/block-sloppy-function.js . I'm not sure which of these are more like V8 regression tests and which are general, and some of these may overlap on things that test262 already tests for.

**Comment by jugglinmike** [comment]
We do have some coverage for those semantics. For example, in [annexB/language/function-code/block-decl-func-skip-early-err.js](https://github.com/tc39/test262/blob/f3bfaa692d70a636c4a2e52ef302199ca71fd52c/test/annexB/language/function-code/block-decl-func-skip-early-err.js):

```js
var init, after;

(function() {
  let f = 123;
  init = f;

  {
    function f() {  }
  }

  after = f;
}());

assert.sameValue(init, 123, 'binding is not initialized to `undefined`');
assert.sameValue(after, 123, 'value is not updated following evaluation');
```

These tests are procedurally generated, so there are actually 40 files following this pattern (files whose name contain `-skip-early-err`). I would have thought these tests were sufficient, but (as evidenced by the current behavior of V8 and JavaScript core) I would have been wrong. Although the example you've shared demonstrates the same algorithm step in Annex B, it is dependent on a completely different early error ([the one defined for Block Statements](https://tc39.github.io/ecma262/#sec-block-static-semantics-early-errors), not [the one defined for Function Definitions](https://tc39.github.io/ecma262/#sec-function-definitions-static-semantics-early-errors)).

This feature is actually dependent on three (mostly) independent circumstances:

1. the position which contains the function declaration; one of: Block,
   IfStatement (x5), or SwitchStatement (x2)
2. the declaration algorithm defining the hoisting extension; one of:
   GlobalDeclarationInstantiation, FunctionDeclarationInstantiation, or
   EvalDeclarationInstantiation
3. the condition that defines an early error which prevents hoisting (maybe
   called, "the disqualifying context"); one of: ScriptBody, FunctionBody,
   BlockStatement, for statement, for-in statement, for-of statement, or switch
   statement (We don't have to worry about the early error for TryStatements or
   ModuleBody because B.3.3 does not apply to those productions)

We're currently using the generation tool to limit the duplication arising from set `#1`, so we'll need to accept the duplication required to cover the cross product of set `#2` and set `#3`.

    | ScriptBody | FnBody | BlockStmt | for | for-in | for-of | switch
----|:----------:|:------:|-----------|-----|--------|--------|-------
GDI |     :heavy_check_mark:      |  n/a   |           |     |        |        |
FDI |    n/a     |   :heavy_check_mark:    |           |     |        |        |
EDI |     :heavy_check_mark:      |  n/a   |           |     |        |        |

Where ":heavy_check_mark:" represents a case for which we currently have coverage, and "n/a" represents an impossible condition.

All this is to say: I expect to resolve this with 15 "case" files, producing about 120 tests.

**Comment by bakkot** [comment]
@jugglinmike, B.3.3 applies to all blocks outside of strict mode, as far as I can tell, which would include the body of any of the clauses of a [TryStatement](https://tc39.github.io/ecma262/#sec-try-statement). Why do you think otherwise?

In particular, catch clauses have an [Early Error](https://tc39.github.io/ecma262/#sec-try-statement-static-semantics-early-errors), which in sloppy mode has [slightly involved static semantics](https://tc39.github.io/ecma262/#sec-variablestatements-in-catch-blocks). If I'm reading B.3.3 and B.3.5 correctly, this means that hoisting would be performed for

```js
try {} catch(e) { function e() {} }
e; // undefined
```

but not e.g.
```js
try {} catch([e]) { function e() {} }
e; // ReferenceError
```

**Comment by jugglinmike** [comment]
I've submitted gh-704 to address this. The patch introduces 200 new files
instead of the expected 120 because we currently generate more files for
EvalDeclarationInstantiation in order to account for distinctions which do not
apply to GlobalDeclarationInstantiation or FunctionDeclaractionInstantiaion
(e.g. "direct vs. indirect").

**Comment by jugglinmike** [comment]
That claim was based on my interpretation of:

> For each FunctionDeclaration f that is directly contained in the
> StatementList of a Block, CaseClause, or DefaultClause Contained within
> script,

Since I could not find a definition of the "Contains" operation for
TryStatement, I assumed that it did *not* Contain Block. But I've just now found
[section 5.3](https://tc39.github.io/ecma262/#sec-static-semantic-rules), which
reads:

> The default definition of Contains is:
> 
> 1. For each terminal and nonterminal grammar symbol, sym, in the definition of this production do
>    a. If sym is the same grammar symbol as symbol, return true.
>    b. If sym is a nonterminal, then
>       i. Let contained be the result of sym Contains symbol.
>       ii. If contained is true, return true.
> 2. Return false. 

So it looks like my patch still needs a little work.

**Comment by jugglinmike** [comment]
> But if you wrap the function declaration in another block, you can still run
> into the situation I'm describing:

Hah, I was playing with exactly this example yesterday, until my erroneous
reading (described above) led me to believe that it was not possible.
